[package]
name = "foil"
version = "0.1.1"
authors = ["Stani <stanislav.pintjuk@gmail.com>"]

[dependencies]
peg-syntax-ext = "0.5.0"
htmlescape = "*"
tempdir = "0.3.6"
fs_extra = "*"

[dependencies.peg]
version = "*"
