[package]
name = "foil"
version = "0.2.0"
authors = ["Stani <stanislav.pintjuk@gmail.com>"]
homepage = "foil.stani.se"

[dependencies]
peg-syntax-ext = "0.5.0"
htmlescape = "*"
tempdir = "0.3.6"
fs_extra = "*"
regex = "0.2"
lazy_static = "*"

[dependencies.peg]
version = "*"
